version: '3.8'

services:
  bot:
    build: .
    container_name: web-to-kindle-bot
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - .:/app  # Bind mount for application code
      - .env:/app/.env:ro  # Mount .env file as read-only